import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="container flex flex-col items-center justify-center min-h-screen p-40 px-0 mx-auto md:py-20 md:p-10 md:px-0 text-3xl font-semibold">
        InTune App
      </div>
    </>
  );
};

export default Home;
